############################
## CHANGE THESE
############################

baseURL: "https://havocsec.me/blogz"
title: Havoc Blogs

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
