############################
## CHANGE THESE
############################

baseURL: "https://Daniel-wambua.github.io/blogz"
title: blogz

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
